# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

pod 'SDWebImage', '~> 3.8.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MBProgressHUD'
pod 'FMDB', '~> 2.6.2'
pod 'AFNetworking'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'BmobSDK'

target '简闻' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 简闻

  target '简闻Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '简闻UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
